name = "UnobservedCountEstimation"
uuid = "27f355fc-deca-4449-8501-6ec19d995810"
authors = ["Piotr Chlebicki"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Copulas = "ae264745-0b69-425e-9d9d-cf662c5eec93"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "0.10"
Copulas = "0.1"
DataFrames = "1"
Distributions = "0.25"
FastGaussQuadrature = "1"
GLM = "1"
Integrals = "4"
Optim = "1"
ProgressMeter = "1"
SpecialFunctions = "2"
Statistics = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
